#line 1 "_build/lexer.c"
#define LEXER

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

#line 8 "_build/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define tlua_yy_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer tlua_yy_create_buffer
#endif

#ifdef yy_delete_buffer
#define tlua_yy_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer tlua_yy_delete_buffer
#endif

#ifdef yy_scan_buffer
#define tlua_yy_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer tlua_yy_scan_buffer
#endif

#ifdef yy_scan_string
#define tlua_yy_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string tlua_yy_scan_string
#endif

#ifdef yy_scan_bytes
#define tlua_yy_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes tlua_yy_scan_bytes
#endif

#ifdef yy_init_buffer
#define tlua_yy_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer tlua_yy_init_buffer
#endif

#ifdef yy_flush_buffer
#define tlua_yy_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer tlua_yy_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define tlua_yy_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state tlua_yy_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define tlua_yy_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer tlua_yy_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define tlua_yypush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state tlua_yypush_buffer_state
#endif

#ifdef yypop_buffer_state
#define tlua_yypop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state tlua_yypop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define tlua_yyensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack tlua_yyensure_buffer_stack
#endif

#ifdef yylex
#define tlua_yylex_ALREADY_DEFINED
#else
#define yylex tlua_yylex
#endif

#ifdef yyrestart
#define tlua_yyrestart_ALREADY_DEFINED
#else
#define yyrestart tlua_yyrestart
#endif

#ifdef yylex_init
#define tlua_yylex_init_ALREADY_DEFINED
#else
#define yylex_init tlua_yylex_init
#endif

#ifdef yylex_init_extra
#define tlua_yylex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra tlua_yylex_init_extra
#endif

#ifdef yylex_destroy
#define tlua_yylex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy tlua_yylex_destroy
#endif

#ifdef yyget_debug
#define tlua_yyget_debug_ALREADY_DEFINED
#else
#define yyget_debug tlua_yyget_debug
#endif

#ifdef yyset_debug
#define tlua_yyset_debug_ALREADY_DEFINED
#else
#define yyset_debug tlua_yyset_debug
#endif

#ifdef yyget_extra
#define tlua_yyget_extra_ALREADY_DEFINED
#else
#define yyget_extra tlua_yyget_extra
#endif

#ifdef yyset_extra
#define tlua_yyset_extra_ALREADY_DEFINED
#else
#define yyset_extra tlua_yyset_extra
#endif

#ifdef yyget_in
#define tlua_yyget_in_ALREADY_DEFINED
#else
#define yyget_in tlua_yyget_in
#endif

#ifdef yyset_in
#define tlua_yyset_in_ALREADY_DEFINED
#else
#define yyset_in tlua_yyset_in
#endif

#ifdef yyget_out
#define tlua_yyget_out_ALREADY_DEFINED
#else
#define yyget_out tlua_yyget_out
#endif

#ifdef yyset_out
#define tlua_yyset_out_ALREADY_DEFINED
#else
#define yyset_out tlua_yyset_out
#endif

#ifdef yyget_leng
#define tlua_yyget_leng_ALREADY_DEFINED
#else
#define yyget_leng tlua_yyget_leng
#endif

#ifdef yyget_text
#define tlua_yyget_text_ALREADY_DEFINED
#else
#define yyget_text tlua_yyget_text
#endif

#ifdef yyget_lineno
#define tlua_yyget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno tlua_yyget_lineno
#endif

#ifdef yyset_lineno
#define tlua_yyset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno tlua_yyset_lineno
#endif

#ifdef yyget_column
#define tlua_yyget_column_ALREADY_DEFINED
#else
#define yyget_column tlua_yyget_column
#endif

#ifdef yyset_column
#define tlua_yyset_column_ALREADY_DEFINED
#else
#define yyset_column tlua_yyset_column
#endif

#ifdef yywrap
#define tlua_yywrap_ALREADY_DEFINED
#else
#define yywrap tlua_yywrap
#endif

#ifdef yyget_lval
#define tlua_yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval tlua_yyget_lval
#endif

#ifdef yyset_lval
#define tlua_yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval tlua_yyset_lval
#endif

#ifdef yyget_lloc
#define tlua_yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc tlua_yyget_lloc
#endif

#ifdef yyset_lloc
#define tlua_yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc tlua_yyset_lloc
#endif

#ifdef yyalloc
#define tlua_yyalloc_ALREADY_DEFINED
#else
#define yyalloc tlua_yyalloc
#endif

#ifdef yyrealloc
#define tlua_yyrealloc_ALREADY_DEFINED
#else
#define yyrealloc tlua_yyrealloc
#endif

#ifdef yyfree
#define tlua_yyfree_ALREADY_DEFINED
#else
#define yyfree tlua_yyfree
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define tlua_yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 118
#define YY_END_OF_BUFFER 119
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[321] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  119,  117,    1,    2,    2,   62,   77,    3,
       64,    5,    6,   21,    7,   62,  117,   68,   68,   10,
       12,   13,   63,   15,   16,   17,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   18,   19,   20,   62,  103,  102,  102,   81,   79,
      101,  103,  103,  103,   80,  107,  104,  105,  105,  106,
      111,  110,  110,  116,  115,  115,  116,  116,    1,    2,
       62,   78,    4,   64,  109,    8,    0,    0,   68,    0,
        0,    0,    0,    0,   11,   14,   63,    0,   63,   24,

       63,   63,   27,   63,   63,   63,   63,   32,   63,   63,
       36,   37,   63,   63,   63,   44,   45,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   69,   69,
      102,   99,  100,  100,   97,    0,    0,   98,    0,   85,
       86,   90,   88,   91,   87,    0,   89,   82,    0,    0,
      104,  105,  110,  115,  113,  114,  108,    9,   67,   67,
        0,   72,   74,    0,    0,   70,   66,   65,   22,   63,
       63,   63,   29,   63,   63,   33,   63,   63,   63,   41,
       63,   63,   63,   63,   63,   49,   63,   51,   63,   63,
       63,   57,   63,   63,   63,   69,    0,    0,    0,    0,

        0,   93,   92,    0,   83,    0,  112,   67,    0,    0,
       67,    0,   72,    0,   74,    0,   76,   75,   70,    0,
       65,   63,   25,   63,   28,   63,   63,   63,   63,   63,
       63,   63,   63,   46,   63,   63,   63,   63,   63,   55,
       56,   63,   63,   60,   73,   71,   94,    0,    0,   84,
       67,    0,   76,    0,   75,    0,   63,   63,   63,   63,
       63,   63,   63,   39,   42,   63,   63,   48,   63,   63,
       63,   58,   59,   63,   73,    0,   71,    0,    0,    0,
       67,    0,   63,   63,   30,   63,   63,   35,   63,   40,
       43,   47,   63,   63,   53,   63,    0,   95,   23,   63,

       63,   34,   38,   50,   63,   63,   63,    0,   26,   63,
       63,   63,   61,    0,   31,   52,   54,    0,   96,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    9,    9,    9,   10,   11,
       12,   13,    9,   14,   15,   16,    9,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,    9,
       22,   23,    9,   24,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   28,   27,   27,   27,   27,   27,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   44,   45,   44,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   55,   56,
       57,   44,   58,   59,   60,   61,    1,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   63,   63,   63,   63,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   65,
       65,   65,   65,   65,   65,   65,   65,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    3,    3,    4,
        1,    1,    3,    1,    3,    5,    6,    6,    6,    3,
        1,    3,    3,    3,    7,    7,    8,    8,    1,    3,
        1,    3,    9,    3,    7,    7,    7,    7,    7,    7,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    3,    1,
        3,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[350] =
    {   0,
        0,    0,   65,  130,  195,  260,   71,   75,   67,   78,
       80,   83,  771,  772,   83,  772,  767,    0,  772,   82,
        0,  756,  772,    0,  772,  745,  751,  310,   81,  743,
      772,  742,  748,  772,  772,    0,   90,   74,   88,   94,
       92,   86,   76,  108,   97,  109,  126,  110,  130,  132,
      135,  772,    0,  772,  100,  772,  772,  760,  772,  772,
      365,  700,  699,  698,  772,  772,  110,  772,  756,  772,
      772,  772,  755,  772,  772,  754,  743,  743,  161,  772,
        0,  772,  772,    0,  742,    0,  737,  151,  187,  156,
      167,  162,  171,    0,    0,    0,  736,  414,  138,  735,

      140,  166,  734,  165,  185,  167,  192,  716,  193,  194,
      712,  195,  196,  199,  198,  696,  206,  208,  212,  205,
      214,  215,  218,  227,  217,  225,  230,  222,  259,  263,
      772,  248,  772,  708,  772,  269,    0,  772,  452,  772,
      772,  772,  772,  772,  772,    0,  772,  772,  648,  647,
      249,  772,  772,  772,  696,  772,  772,  772,  314,  286,
      282,  276,  338,  254,    0,  672,    0,  675,  275,  267,
      281,  268,  668,  295,  296,  297,  292,  305,  298,  667,
      302,  304,  329,  332,  322,  666,  301,  342,  323,  343,
      346,  652,  344,  345,  338,  423,  391,  346,    0,  385,

        0,  772,  772,    0,  772,  603,  772,  433,  413,  395,
      436,  469,  374,  472,  474,  477,  480,  631,  630,  629,
      645,  371,  604,  326,  603,  358,  409,  383,  454,  380,
      365,  455,  485,  600,  410,  429,  487,  363,  427,  596,
      594,  488,  490,  492,  498,  575,  772,    0,    0,  772,
      500,  503,  506,  508,  574,  573,  495,  493,  496,  516,
      498,  518,  520,  521,  588,  522,  524,  587,  526,  527,
      531,  586,  585,  532,  534,  536,  567,  566,    0,    0,
      542,  547,  539,  533,  580,  554,  540,  576,  546,  451,
      449,  447,  557,  558,  560,  561,    0,  772,  444,  566,

      568,  442,  370,  236,  571,  572,  575,    0,  221,  577,
      578,  579,  155,    0,  148,  142,   87,    0,  772,  772,
      623,  632,  641,  650,  657,  663,  669,  673,  678,  682,
      689,  693,  695,  697,  704,  710,  714,  716,  718,  720,
      724,  728,  730,  732,  734,  736,  738,  740,  742
    } ;

static const flex_int16_t yy_def[350] =
    {   0,
      320,    1,  321,  321,  321,  321,  322,  322,  323,  323,
      324,  324,  320,  320,  320,  320,  320,  325,  320,  325,
      326,  320,  320,  325,  320,  325,  320,  320,  320,  325,
      320,  325,  327,  320,  320,  325,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  320,  325,  320,  325,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      325,  320,  320,  326,  320,  325,  320,  320,  320,  320,
      320,  320,  320,  328,  325,  325,  327,  329,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  320,  320,
      320,  320,  320,  320,  320,  320,  330,  320,  331,  320,
      320,  320,  320,  320,  320,  332,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  333,  334,  335,  336,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  320,  320,  320,  337,  320,

      338,  320,  320,  339,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  340,  334,  334,
      336,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  320,  341,  320,  342,  343,  320,
      320,  320,  320,  320,  340,  340,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  320,  320,  341,  341,  344,  345,
      320,  320,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  327,  327,  327,  346,  320,  327,  327,

      327,  327,  327,  327,  327,  327,  327,  347,  327,  327,
      327,  327,  327,  348,  327,  327,  327,  349,  320,    0,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320
    } ;

static const flex_int16_t yy_nxt[838] =
    {   0,
       14,   15,   16,   17,   15,   18,   19,   20,   18,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   30,
       31,   32,   18,   18,   33,   33,   33,   33,   34,   18,
       35,   18,   36,   18,   37,   33,   38,   39,   40,   41,
       33,   42,   43,   33,   44,   45,   46,   33,   33,   47,
       48,   49,   33,   50,   51,   33,   33,   52,   53,   54,
       55,   14,   14,   14,   14,   56,   56,   57,   58,   72,
       73,   60,   67,   68,   69,   67,   67,   68,   69,   67,
       72,   73,   75,   76,   79,   75,   76,   79,   82,   98,
       77,   98,   78,   77,   61,   78,   88,   89,   89,   89,

       70,   98,   98,   98,   70,   98,   90,   98,  101,   98,
       83,  151,   98,   91,  151,  111,  129,  130,  130,   90,
      110,  112,  102,   98,   98,   98,   56,   62,   63,   64,
       56,   56,   57,   58,  103,   99,   60,  108,  104,  105,
      100,   98,  106,  115,  109,   98,  113,   98,  116,  107,
       98,  121,  122,   98,  114,   98,  117,   98,  118,   61,
      119,  123,   79,   98,  120,   79,  126,  159,  159,  159,
       98,  124,  160,  160,  160,  169,  127,  128,  162,  162,
       98,   98,   98,   89,   89,   89,  125,  163,  163,  163,
      170,   56,   62,   63,   64,   56,   56,   57,   58,   91,

       98,   65,   88,   89,   89,   89,  164,   98,   98,   98,
       98,   98,   90,   98,   98,  172,  161,  171,  174,   91,
       98,   98,  173,   98,   61,   90,  165,   98,  175,   98,
       98,  178,   98,   98,  179,  181,   98,   98,  176,  177,
       98,  186,   98,  182,  183,   98,  184,  180,  187,  132,
      151,   98,  132,  151,  185,  188,   56,   62,   63,   64,
       56,   56,   57,   58,  191,  190,   65,  189,  193,  192,
      217,  217,  194,  195,   88,  196,  196,  196,   88,  196,
      196,  196,   98,   98,   90,  200,  200,  200,   90,   61,
       98,  197,  213,  213,  198,  197,   98,   90,  160,  160,

      160,   90,  211,  211,  211,  223,  225,   98,  214,  222,
       98,   98,   98,   98,  199,  224,   98,   98,  212,   98,
       98,   56,   62,   63,   64,   88,   89,   89,   89,  229,
      208,  208,  208,  228,  227,   90,  232,   98,   98,  209,
      231,   98,   91,  233,   98,   92,  210,   98,   90,  230,
      237,  226,  209,   98,  215,  215,  215,   98,   98,   98,
       98,   98,  245,  245,   93,   94,  132,  133,  134,  132,
      216,  135,  236,   98,  234,  239,  235,  258,   98,  244,
       98,  136,  136,  136,  241,   98,   98,  238,  240,  243,
      213,  213,  137,  242,  138,   98,  139,  270,   98,  140,

      141,  247,  247,  247,  142,  259,  214,  196,  196,  196,
      143,  208,  208,  208,  144,  257,  145,  146,  147,  167,
      264,  167,  167,  197,   98,   98,  167,  210,  167,  251,
      251,  251,  263,  167,  261,  167,  167,  167,   88,  196,
      196,  196,   98,  167,   98,  167,  167,  167,   90,  208,
      208,  208,  211,  211,  211,  197,  260,   98,  209,   98,
      267,   90,   98,  271,   98,  210,   98,  268,  212,   98,
       98,  209,  167,  252,  167,  203,  203,  203,  203,  203,
      203,  203,  203,  203,  203,  211,  211,  211,  213,  213,
      215,  215,  215,  215,  215,  215,  253,  253,  262,  265,

       98,  212,   98,   98,  214,   98,  216,   98,   98,  216,
       98,   98,  254,   98,  275,  275,  281,  281,  281,  251,
      251,  251,  253,  253,  253,  253,  272,  266,  273,  269,
      276,   98,  282,   98,  285,   98,   98,   98,  254,   98,
      254,   98,   98,  274,  287,  283,   98,   98,   98,  284,
      275,  275,  275,  275,   98,   98,  288,  289,  281,  281,
      281,   98,  292,  281,  281,  281,  276,  286,  276,   98,
      290,  293,   98,   98,  282,   98,   98,  291,  294,  282,
      300,   98,  295,   98,  303,  299,   98,   98,  296,  302,
       98,   98,   98,   98,   98,   98,  301,  304,  278,  278,

       98,   98,   98,   98,  309,  256,  256,  278,  307,   98,
      305,   98,  306,  313,  310,   98,  316,  317,   98,   98,
      311,  312,  315,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   81,
       98,  220,  220,  256,  250,   81,   84,   98,   84,   84,
       84,   84,   97,   97,   97,   97,   97,   97,  166,  166,
      168,   98,   98,   98,  168,  168,  168,  201,  201,  202,
       98,  202,  202,  202,  202,  202,  202,  202,  204,  204,

      218,  218,  219,  219,  220,  219,  167,  207,  206,  205,
      133,   98,  167,  221,  221,  221,  221,  221,  221,  246,
      246,  248,  248,  249,  249,  255,  255,   98,  255,  277,
      277,   98,  277,  279,  279,  280,  280,  297,  297,  298,
      298,  308,  308,  314,  314,  318,  318,  319,  319,   98,
       98,   98,  158,  157,  156,  155,  154,  153,  152,  150,
      149,  148,  131,   98,   96,   95,   87,   86,   85,   80,
      320,   13,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320
    } ;

static const flex_int16_t yy_chk[838] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    3,    3,    9,
        9,    3,    7,    7,    7,    7,    8,    8,    8,    8,
       10,   10,   11,   11,   15,   12,   12,   15,   20,   38,
       11,   43,   11,   12,    3,   12,   29,   29,   29,   29,

        7,   42,  317,   39,    8,   37,   29,   41,   38,   40,
       20,   67,   45,   29,   67,   43,   55,   55,   55,   29,
       42,   43,   39,   44,   46,   48,    3,    3,    3,    3,
        4,    4,    4,    4,   39,   37,    4,   41,   40,   40,
       37,   47,   40,   45,   41,   49,   44,   50,   46,   40,
       51,   48,   48,   99,   44,  101,   46,  316,   46,    4,
       47,   48,   79,  315,   47,   79,   50,   88,   88,   88,
      313,   49,   90,   90,   90,   99,   51,   51,   92,   92,
      104,  102,  106,   91,   91,   91,   49,   93,   93,   93,
      101,    4,    4,    4,    4,    5,    5,    5,    5,   91,

      105,    5,   89,   89,   89,   89,   93,  107,  109,  110,
      112,  113,   89,  115,  114,  104,   90,  102,  106,   89,
      120,  117,  105,  118,    5,   89,   93,  119,  107,  121,
      122,  112,  125,  123,  112,  114,  309,  128,  109,  110,
      126,  120,  124,  115,  117,  127,  118,  113,  121,  132,
      151,  304,  132,  151,  119,  122,    5,    5,    5,    5,
        6,    6,    6,    6,  125,  124,    6,  123,  127,  126,
      164,  164,  127,  128,  129,  129,  129,  129,  130,  130,
      130,  130,  170,  172,  129,  136,  136,  136,  130,    6,
      169,  129,  162,  162,  129,  130,  171,  129,  161,  161,

      161,  130,  160,  160,  160,  170,  172,  177,  162,  169,
      174,  175,  176,  179,  129,  171,  187,  181,  160,  182,
      178,    6,    6,    6,    6,   28,   28,   28,   28,  177,
      159,  159,  159,  176,  175,   28,  181,  185,  189,  159,
      179,  224,   28,  182,  183,   28,  159,  184,   28,  178,
      187,  174,  159,  195,  163,  163,  163,  188,  190,  193,
      194,  191,  198,  198,   28,   28,   61,   61,   61,   61,
      163,   61,  185,  226,  183,  189,  184,  224,  238,  195,
      231,   61,   61,   61,  191,  303,  222,  188,  190,  194,
      213,  213,   61,  193,   61,  230,   61,  238,  228,   61,

       61,  200,  200,  200,   61,  226,  213,  197,  197,  197,
       61,  210,  210,  210,   61,  222,   61,   61,   61,   98,
      231,   98,   98,  197,  227,  235,   98,  210,   98,  209,
      209,  209,  230,   98,  228,   98,   98,   98,  196,  196,
      196,  196,  239,   98,  236,   98,   98,   98,  196,  208,
      208,  208,  211,  211,  211,  196,  227,  302,  208,  299,
      235,  196,  292,  239,  291,  208,  290,  236,  211,  229,
      232,  208,   98,  209,   98,  139,  139,  139,  139,  139,
      139,  139,  139,  139,  139,  212,  212,  212,  214,  214,
      215,  215,  215,  216,  216,  216,  217,  217,  229,  232,

      233,  212,  237,  242,  214,  243,  215,  244,  258,  216,
      257,  259,  217,  261,  245,  245,  251,  251,  251,  252,
      252,  252,  253,  253,  254,  254,  242,  233,  243,  237,
      245,  260,  251,  262,  259,  263,  264,  266,  253,  267,
      254,  269,  270,  244,  261,  257,  271,  274,  284,  258,
      275,  275,  276,  276,  283,  287,  262,  263,  281,  281,
      281,  289,  267,  282,  282,  282,  275,  260,  276,  286,
      264,  269,  293,  294,  281,  295,  296,  266,  270,  282,
      284,  300,  271,  301,  289,  283,  305,  306,  274,  287,
      307,  288,  310,  311,  312,  285,  286,  293,  278,  277,

      273,  272,  268,  265,  300,  256,  255,  246,  296,  241,
      294,  240,  295,  307,  301,  234,  311,  312,  225,  223,
      305,  306,  310,  321,  321,  321,  321,  321,  321,  321,
      321,  321,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  323,  323,  323,  323,  323,  323,  323,  323,  323,
      324,  324,  324,  324,  324,  324,  324,  324,  324,  325,
      221,  220,  219,  218,  206,  325,  326,  192,  326,  326,
      326,  326,  327,  327,  327,  327,  327,  327,  328,  328,
      329,  186,  180,  173,  329,  329,  329,  330,  330,  331,
      168,  331,  331,  331,  331,  331,  331,  331,  332,  332,

      333,  333,  334,  334,  166,  334,  335,  155,  150,  149,
      134,  116,  335,  336,  336,  336,  336,  336,  336,  337,
      337,  338,  338,  339,  339,  340,  340,  111,  340,  341,
      341,  108,  341,  342,  342,  343,  343,  344,  344,  345,
      345,  346,  346,  347,  347,  348,  348,  349,  349,  103,
      100,   97,   87,   85,   78,   77,   76,   73,   69,   64,
       63,   62,   58,   33,   32,   30,   27,   26,   22,   17,
       13,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "src/lexer.l"

#line 9 "src/lexer.l"
#include <stdbool.h>
#include <stdio.h>
#include "tlua/alloc.h"
#include "tlua/lexer.h"

#define YYSTYPE tlua_token_value
#define YYLTYPE struct region

#define YY_USER_ACTION                           \
    yycolumn += yyleng;                          \
    yylloc->left.line    = yylloc->right.line;   \
    yylloc->left.column  = yylloc->right.column; \
    yylloc->right.line   = yylineno;             \
    yylloc->right.column = yycolumn;             \

#define YY_USER_INIT                               \
    yylloc->left.line = yylloc->right.line = 1;    \
    yylloc->left.column = yylloc->right.column = 0;

#define newline() do {                   \
    yylloc->right.line = ++yylineno;     \
    yylloc->right.column = yycolumn = 0; \
} while(0)

#define memdup(p, n) alloc_copy(&yyextra->alloc, p, n)
#define errorl(str) error(yyextra, &yylloc->left, &yylloc->right, str)
#define errort(str) error(yyextra, &yyextra->saved_left, &yylloc->right, str)
static void error(tlua_lexstate *, const struct sourcepos *l, const struct sourcepos *r, const char *);
static double parse_real(char *, int);
static lua_Unsigned parse_word(char *, int);
static struct tlua_int_token parse_int(char *, int, bool);
static void text_add_char(tlua_lexstate *, char);
static void text_add_str(tlua_lexstate *, char *, int);
#line 991 "_build/lexer.c"
/* Remove unused functions */
#define YY_NO_INPUT 1

#line 995 "_build/lexer.c"

#define INITIAL 0
#define STRING 1
#define CHAR 2
#define TEXT_FMT 3
#define LINE_COMMENT 4
#define BLOCK_COMMENT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE tlua_lexstate *

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state ( int _new_state , yyscan_t yyscanner);
    
    static void yy_pop_state ( yyscan_t yyscanner );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 80 "src/lexer.l"


#line 1261 "_build/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 321 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 772 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "src/lexer.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 83 "src/lexer.l"
{ newline(); }
	YY_BREAK
/* Reserved symbols */
case 3:
YY_RULE_SETUP
#line 85 "src/lexer.l"
{ return T_HASH;         }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 86 "src/lexer.l"
{ return T_HASHLBRACKET; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "src/lexer.l"
{ return T_LPAREN;       }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 88 "src/lexer.l"
{ return T_RPAREN;       }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 89 "src/lexer.l"
{ return T_COMMA;        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "src/lexer.l"
{ return T_ARROW;        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 91 "src/lexer.l"
{ return T_DOTDOTDOT;    }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "src/lexer.l"
{ return T_COLON;        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "src/lexer.l"
{ return T_COLONGT;      }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "src/lexer.l"
{ return T_SEMICOLON;    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "src/lexer.l"
{ return T_EQUALOP;      }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 96 "src/lexer.l"
{ return T_DARROW;       }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 97 "src/lexer.l"
{ return T_LBRACKET;     }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 98 "src/lexer.l"
{ return T_RBRACKET;     }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 99 "src/lexer.l"
{ return T_WILD;         }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 100 "src/lexer.l"
{ return T_LBRACE;       }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 101 "src/lexer.l"
{ return T_BAR;          }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 102 "src/lexer.l"
{ return T_RBRACE;       }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "src/lexer.l"
{ return T_ASTERISK;     }
	YY_BREAK
/* Reserved keywords */
case 22:
YY_RULE_SETUP
#line 106 "src/lexer.l"
{ return T_AND;       }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 107 "src/lexer.l"
{ return T_ANDALSO;   }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 108 "src/lexer.l"
{ return T_AS;        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 109 "src/lexer.l"
{ return T_CASE;      }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "src/lexer.l"
{ return T_DATATYPE;  }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 111 "src/lexer.l"
{ return T_DO;        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 112 "src/lexer.l"
{ return T_ELSE;      }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 113 "src/lexer.l"
{ return T_END;       }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "src/lexer.l"
{ return T_EQTYPE;    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 115 "src/lexer.l"
{ return T_EXCEPTION; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 116 "src/lexer.l"
{ return T_FN;        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 117 "src/lexer.l"
{ return T_FUN;       }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 118 "src/lexer.l"
{ return T_FUNCTOR;   }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 119 "src/lexer.l"
{ return T_HANDLE;    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 120 "src/lexer.l"
{ return T_IF;        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 121 "src/lexer.l"
{ return T_IN;        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 122 "src/lexer.l"
{ return T_INCLUDE;   }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 123 "src/lexer.l"
{ return T_INFIX;     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 124 "src/lexer.l"
{ return T_INFIXR;    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 125 "src/lexer.l"
{ return T_LET;       }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 126 "src/lexer.l"
{ return T_LOCAL;     }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 127 "src/lexer.l"
{ return T_NONFIX;    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 128 "src/lexer.l"
{ return T_OF;        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "src/lexer.l"
{ return T_OP;        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 130 "src/lexer.l"
{ return T_OPEN;      }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 131 "src/lexer.l"
{ return T_ORELSE;    }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 132 "src/lexer.l"
{ return T_RAISE;     }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 133 "src/lexer.l"
{ return T_REC;       }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 134 "src/lexer.l"
{ return T_SHARING;   }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 135 "src/lexer.l"
{ return T_SIG;       }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 136 "src/lexer.l"
{ return T_SIGNATURE; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 137 "src/lexer.l"
{ return T_STRUCT;    }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 138 "src/lexer.l"
{ return T_STRUCTURE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 139 "src/lexer.l"
{ return T_THEN;      }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 140 "src/lexer.l"
{ return T_TYPE;      }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 141 "src/lexer.l"
{ return T_VAL;       }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 142 "src/lexer.l"
{ return T_WHERE;     }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 143 "src/lexer.l"
{ return T_WHILE;     }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "src/lexer.l"
{ return T_WITH;      }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 145 "src/lexer.l"
{ return T_WITHTYPE;  }
	YY_BREAK
/* Identifier types */
case 62:
YY_RULE_SETUP
#line 148 "src/lexer.l"
{ yylval->ident = memdup(yytext, yyleng+1); return T_SHORTSYMID;      }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 149 "src/lexer.l"
{ yylval->ident = memdup(yytext, yyleng+1); return T_SHORTALPHANUMID; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 150 "src/lexer.l"
{ yylval->ident = memdup(yytext, yyleng+1); return T_TYVARID;         }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 151 "src/lexer.l"
{ yylval->ident = memdup(yytext, yyleng+1); return T_LONGALPHANUMID;  }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 152 "src/lexer.l"
{ yylval->ident = memdup(yytext, yyleng+1); return T_LONGSYMID;       }
	YY_BREAK
/* Numeric constants */
case 67:
YY_RULE_SETUP
#line 155 "src/lexer.l"
{ yylval->real = parse_real(yytext, yyleng); return T_REAL; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 156 "src/lexer.l"
{ yylval->integer = parse_int(yytext+0, 10, false); return T_INT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 157 "src/lexer.l"
{ yylval->integer = parse_int(yytext+1, 10, true);  return T_INT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 158 "src/lexer.l"
{ yylval->integer = parse_int(yytext+2, 16, false); return T_INT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 159 "src/lexer.l"
{ yylval->integer = parse_int(yytext+3, 16, true);  return T_INT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 160 "src/lexer.l"
{ yylval->integer = parse_int(yytext+2, 2, false);  return T_INT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 161 "src/lexer.l"
{ yylval->integer = parse_int(yytext+3, 2, true);   return T_INT; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 162 "src/lexer.l"
{ yylval->word = parse_word(yytext+2, 10); return T_WORD; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 163 "src/lexer.l"
{ yylval->word = parse_word(yytext+3, 16); return T_WORD; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 164 "src/lexer.l"
{ yylval->word = parse_word(yytext+3, 2);  return T_WORD; }
	YY_BREAK
/* String and character literals */
case 77:
YY_RULE_SETUP
#line 167 "src/lexer.l"
{
    yyextra->text.buf = malloc(16);
    if (!yyextra->text.buf)
        abort();
    yyextra->text.len = 0;
    yyextra->text.size = 16;
    yyextra->saved_left.line = yylloc->left.line;
    yyextra->saved_left.column = yylloc->left.column;
    yy_push_state(STRING, yyscanner);
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 177 "src/lexer.l"
{
    yyextra->text.buf = malloc(2);
    if (!yyextra->text.buf)
        abort();
    yyextra->text.len = 0;
    yyextra->text.size = 2;
    yyextra->saved_left.line = yylloc->left.line;
    yyextra->saved_left.column = yylloc->left.column;
    yy_push_state(CHAR, yyscanner);
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 188 "src/lexer.l"
{
    yylval->string.buf = alloc_copy(&yyextra->alloc, yyextra->text.buf, yyextra->text.len);
    yylval->string.len = yyextra->text.len;
    free(yyextra->text.buf);
    yy_pop_state(yyscanner);
    return T_STRING;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 195 "src/lexer.l"
{
    if (yyextra->text.len != 1) {
        errort("Character constant not of size 1");
    }
    yylval->chr = yyextra->text.len > 0 ? yyextra->text.buf[0] : '\0';
    free(yyextra->text.buf);
    yy_pop_state(yyscanner);
    return T_CHAR;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 205 "src/lexer.l"
{ text_add_str(yyextra, yytext, yyleng); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 206 "src/lexer.l"
{ text_add_str(yyextra, yytext, yyleng); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 207 "src/lexer.l"
{ text_add_str(yyextra, yytext, yyleng); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 208 "src/lexer.l"
{ text_add_str(yyextra, yytext, yyleng); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 209 "src/lexer.l"
{ text_add_char(yyextra, '\a'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 210 "src/lexer.l"
{ text_add_char(yyextra, '\b'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 211 "src/lexer.l"
{ text_add_char(yyextra, '\t'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 212 "src/lexer.l"
{ text_add_char(yyextra, '\n'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 213 "src/lexer.l"
{ text_add_char(yyextra, '\v'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 214 "src/lexer.l"
{ text_add_char(yyextra, '\f'); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 215 "src/lexer.l"
{ text_add_char(yyextra, '\r'); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 216 "src/lexer.l"
{ text_add_char(yyextra, yytext[2] - '@'); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 217 "src/lexer.l"
{ errorl("Illegal control escape in text constant; must be one of @ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 218 "src/lexer.l"
{
    long n = strtol(yytext + 2, NULL, 10);
    if (0 <= n && n <= 255) {
        text_add_char(yyextra, (char)n);
    } else {
        errorl("Numeric escape out of bounds");
    }
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 226 "src/lexer.l"
{
    long n = strtol(yytext + 2, NULL, 16);
    if (0 <= n && n <= 255) {
        text_add_char(yyextra, (char)n);
    } else {
        errorl("Numeric escape out of bounds\n");
    }
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 234 "src/lexer.l"
{
    long n = strtol(yytext + 2, NULL, 16);
    if (0 <= n && n <= 255) {
        text_add_char(yyextra, (char)n);
    } else {
        errorl("Numeric escape out of bounds\n");
    }
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 242 "src/lexer.l"
{ text_add_char(yyextra, '"'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 243 "src/lexer.l"
{ text_add_char(yyextra, '\\'); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 244 "src/lexer.l"
{ yy_push_state(TEXT_FMT, yyscanner); }
	YY_BREAK
case 100:
/* rule 100 can match eol */
YY_RULE_SETUP
#line 245 "src/lexer.l"
{ newline(); yy_push_state(TEXT_FMT, yyscanner); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 246 "src/lexer.l"
{ errorl("Illegal escape in text constant\n"); }
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 247 "src/lexer.l"
{
    errorl("Unclosed text constant at eol\n");
    newline();
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 251 "src/lexer.l"
{ errorl("Illegal character in text constant\n"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 253 "src/lexer.l"
;
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 254 "src/lexer.l"
{ newline(); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 255 "src/lexer.l"
{ yy_pop_state(yyscanner); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 256 "src/lexer.l"
{ errorl("Illegal formatting character in text continuation\n"); }
	YY_BREAK
/* Comments */
case 108:
YY_RULE_SETUP
#line 259 "src/lexer.l"
{ yy_push_state(LINE_COMMENT, yyscanner); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 260 "src/lexer.l"
{ yy_push_state(BLOCK_COMMENT, yyscanner); }
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 262 "src/lexer.l"
{ newline(); yy_pop_state(yyscanner); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 263 "src/lexer.l"
;
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 265 "src/lexer.l"
{ yy_push_state(LINE_COMMENT, yyscanner); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 266 "src/lexer.l"
{ yy_push_state(BLOCK_COMMENT, yyscanner); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 267 "src/lexer.l"
{ yy_pop_state(yyscanner); }
	YY_BREAK
case 115:
/* rule 115 can match eol */
YY_RULE_SETUP
#line 268 "src/lexer.l"
{ newline(); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 269 "src/lexer.l"
;
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 271 "src/lexer.l"
{ errorl("Illegal token"); return T_EOF; }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 273 "src/lexer.l"
{
    errort("Unterminated string constant");
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 276 "src/lexer.l"
{
    errort("Unterminated character constant");
}
	YY_BREAK
case YY_STATE_EOF(BLOCK_COMMENT):
#line 279 "src/lexer.l"
{
    errort("Unterminated block comment");
}
	YY_BREAK
case YY_STATE_EOF(LINE_COMMENT):
#line 282 "src/lexer.l"
{
    /* Check if we're nested inside a block comment */
    if (yyg->yy_start_stack_ptr > 1) {
        errort("Unterminated block comment");
    }
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 289 "src/lexer.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 2003 "_build/lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TEXT_FMT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 321 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 321 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 320);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

    static void yy_push_state (int  _new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = (yy_size_t) yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) yyalloc( new_size , yyscanner );

		else
			yyg->yy_start_stack = (int *) yyrealloc(
					(void *) yyg->yy_start_stack, new_size , yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

#define YYTABLES_NAME "yytables"

#line 289 "src/lexer.l"


static double parse_real(char *str, int len)
{
    int i, j;

    for (i = 0; i < len; i++) {
        if (str[i] == '~') {
            str[i] = '-';
        }
        if (str[i] == '_') {
            for (j = i; j < len - 1; j++) {
                str[j] = str[j + 1];
            }
            str[len - 1] = '\0';
            len--;
            i--; /* Redo the same check on the shifted char */
        }
    }
    return lua_str2number(str, NULL);
}

static lua_Unsigned parse_word(char *str, int radix)
{
    lua_Unsigned w = 0;
    int i;

    for (i = 0; str[i]; i++) {
        if ('0' <= str[i] && str[i] <= '9')
            w = w * radix + str[i] - '0';
        else if (str[i] == '_')
            ;
        else if ('a' <= str[i] && str[i] <= 'f')
            w = w * radix + str[i] - 'a';
        else if ('A' <= str[i] && str[i] <= 'F')
            w = w * radix + str[i] - 'A';
        else
            abort();
    }
    return w;
}

static struct tlua_int_token parse_int(char *str, int radix, bool negate)
{
    lua_Integer n = 0;
    bool underscores = false;
    struct tlua_int_token s;
    int i;

    for (i = 0; str[i]; i++) {
        if ('0' <= str[i] && str[i] <= '9')
            n = n * radix + str[i] - '0';
        else if (str[i] == '_')
            underscores = true;
        else if ('a' <= str[i] && str[i] <= 'f')
            n = n * radix + str[i] - 'a';
        else if ('A' <= str[i] && str[i] <= 'F')
            n = n * radix + str[i] - 'A';
        else
            abort();
    }

    s.val = negate ? -n : n;
    s.isdigit = str[1] == '\0' && !underscores && !negate && radix == 10;
    s.isfield = str[0] != '0' && !underscores && !negate && radix == 10;
    return s;
}

static void text_add_char(tlua_lexstate *lexstate, char c)
{
    text_add_str(lexstate, &c, 1);
}

static int next_pow2(int n)
{
    n--;
    n |= n >> 1;
    n |= n >> 2;
    n |= n >> 4;
    n |= n >> 8;
    n |= n >> 16;
    n++;
    return n;
}

static void text_add_str(tlua_lexstate *lexstate, char *str, int len)
{
    if (lexstate->text.len + len >= lexstate->text.size) {
        lexstate->text.size = next_pow2(lexstate->text.len + len);
        lexstate->text.buf = realloc(lexstate->text.buf, lexstate->text.size);
    }
    memcpy(lexstate->text.buf + lexstate->text.len, str, len);
    lexstate->text.len += len;
}

static void error(
    tlua_lexstate *lexstate,
    const struct sourcepos *left,
    const struct sourcepos *right,
    const char *str)
{
    /* TODO: Error handling */
    fprintf(stderr, "Error: %s\n", str);
    /* int written; */
    /* tlua_error *e; */

    /* e = tlua_alloc_alloc(&lexstate->alloc, sizeof(tlua_error)); */

    /* written = snprintf(e->message, sizeof e->message, "Error: %d.%d-%d.%d ", */
        /* first_line, first_column, last_line, last_column); */
    /* if (written < 0) */
        /* abort(); */

    /* strncpy(e->message + written, str, sizeof e->message - written); */
    /* e->message[sizeof e->message - 1] = '\0'; */
    /* e->next = lexstate->errors; */
    /* lexstate->errors = e; */
}

void *yyalloc(size_t sz, yyscan_t scanner)
{
    struct alloc *alloc = &((struct yyguts_t *)scanner)->yyextra_r->alloc;
    size_t *mem = rawalloc(alloc, sz + sizeof(size_t));
    *mem = sz + sizeof(size_t);
    return mem + 1;
}
void *yyrealloc(void *p, size_t sz, yyscan_t scanner)
{
    struct alloc *alloc = &((struct yyguts_t *)scanner)->yyextra_r->alloc;
    size_t *mem = p;
    mem = mem - 1;
    mem = rawrealloc(alloc, mem, *mem, sz + sizeof(size_t));
    *mem = sz + sizeof(size_t);
    return mem + 1;
}
void yyfree(void *p, yyscan_t scanner)
{
    if (p) {
        struct alloc *alloc = &((struct yyguts_t *)scanner)->yyextra_r->alloc;
        size_t *mem = p;
        mem = mem - 1;
        rawfree(alloc, mem, *mem);
    }
}



